"""
Test suite for Securities Master Gold Layer — baseline quality checks.
Generated by SML BMAD QA Agent. Regenerated per ticket with per-REQ test cases.

Tables:
  statestreet.g_statestreet.securities_master
"""

import pytest
from pyspark.sql import SparkSession
from pyspark.sql import functions as F


GOLD_TABLE = "statestreet.g_statestreet.securities_master"

REQUIRED_COLUMNS = [
    "product_id",
    "product_name",
    "type",
    "sub_type",
    "status",
    "is_current",
    "effective_start_date",
    "effective_end_date",
    "_gold_built_at",
]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def spark() -> SparkSession:
    try:
        from databricks.connect import DatabricksSession  # type: ignore
        session = DatabricksSession.builder.getOrCreate()
    except ImportError:
        session = (
            SparkSession.builder.master("local[*]")
            .appName("test_gold_baseline")
            .getOrCreate()
        )
    yield session
    session.stop()


@pytest.fixture(scope="session")
def gold_df(spark: SparkSession):
    return spark.table(GOLD_TABLE)


@pytest.fixture(scope="session")
def gold_current_df(gold_df):
    return gold_df.filter(F.col("is_current") == True)  # noqa: E712


# ---------------------------------------------------------------------------
# Baseline Gold Table Checks
# ---------------------------------------------------------------------------


class TestGoldTableBaseline:
    """Baseline checks: table exists, has rows, has required columns."""

    def test_gold_table_has_rows(self, gold_df):
        """Gold table must contain at least one row."""
        assert gold_df.count() > 0, (
            f"Gold table '{GOLD_TABLE}' is empty."
        )

    def test_gold_table_has_required_columns(self, gold_df):
        """Gold table must have all required structural columns."""
        col_names = {f.name.lower() for f in gold_df.schema.fields}
        missing = [c for c in REQUIRED_COLUMNS if c.lower() not in col_names]
        assert not missing, (
            f"Gold table is missing required columns: {missing}"
        )

    def test_product_id_is_not_null(self, gold_df):
        """product_id must never be NULL — it is the grain key."""
        null_count = gold_df.filter(F.col("product_id").isNull()).count()
        assert null_count == 0, (
            f"{null_count} rows have NULL product_id in the gold table."
        )

    def test_is_current_flag_is_boolean(self, gold_df):
        """is_current must contain only TRUE or FALSE values."""
        invalid = gold_df.filter(
            ~F.col("is_current").isin(True, False)
        ).count()
        assert invalid == 0, (
            f"{invalid} rows have invalid is_current values (expected TRUE or FALSE)."
        )

    def test_current_rows_have_no_end_date(self, gold_current_df):
        """Rows with is_current=TRUE must have effective_end_date = '9999-12-31'."""
        bad = gold_current_df.filter(
            F.col("effective_end_date") != F.lit("9999-12-31")
        ).count()
        assert bad == 0, (
            f"{bad} current rows (is_current=TRUE) have effective_end_date != 9999-12-31."
        )

    def test_gold_built_at_is_not_null(self, gold_df):
        """_gold_built_at must be populated on every row."""
        null_count = gold_df.filter(F.col("_gold_built_at").isNull()).count()
        assert null_count == 0, (
            f"{null_count} rows have NULL _gold_built_at."
        )
