from __future__ import annotations
"""
deploy_agent.py
Deploy Agent — validates and deploys Databricks Asset Bundle.
Also provides job status, trigger utilities, and GitHub PR creation.
"""

import os
import shutil
import subprocess
from pathlib import Path

import git
from rich.console import Console

from agents.context_loader import PROJECT_ROOT, STATESTREET_ROOT
REPO_ROOT = PROJECT_ROOT
console = Console()


_REQUIRED_NOTEBOOKS = [
    "notebooks/03_bronze_ingest.py",
    "notebooks/04_silver_conform.sql",
    "notebooks/05_gold_build.sql",
]


def _check_notebooks():
    """Raise a clear error if any bundle notebook is missing (SETUP-017 / ISSUE-025)."""
    missing = [nb for nb in _REQUIRED_NOTEBOOKS if not (REPO_ROOT / nb).exists()]
    if missing:
        raise RuntimeError(
            "Cannot deploy — the following notebooks are missing from project/notebooks/:\n"
            + "\n".join(f"  ✗ {nb}" for nb in missing)
            + "\n\nRun Beat 4 (Developer Agent) first to generate all notebooks."
        )


def deploy(use_case_name: str):
    """Run: databricks bundle validate + deploy."""
    _check_notebooks()

    # Auto-detect local Terraform to avoid 'openpgp: key expired' checksum error
    if not os.environ.get("DATABRICKS_TF_EXEC_PATH"):
        tf = shutil.which("terraform")
        if tf:
            os.environ["DATABRICKS_TF_EXEC_PATH"] = tf
            console.print(f"[dim]  Using local Terraform: {tf}[/]")

    console.print("[bold cyan][DEPLOY][/] Validating bundle...")
    _run("databricks bundle validate", cwd=REPO_ROOT)

    console.print("[bold cyan][DEPLOY][/] Deploying bundle to Databricks...")
    _run("databricks bundle deploy", cwd=REPO_ROOT)

    console.print("[bold green][DEPLOY] Bundle deployed successfully![/]")


def get_job_status(job_name: str):
    """Print active and recent job runs."""
    console.print(f"[bold cyan][STATUS][/] Active runs (job: {job_name}):")
    _run_streaming("databricks jobs list-runs --active-only", cwd=REPO_ROOT)
    console.print(f"[bold cyan][STATUS][/] Recent runs (last 5):")
    _run_streaming("databricks jobs list-runs --limit 5", cwd=REPO_ROOT)


def trigger_job(job_name: str):
    """Trigger a Databricks job and wait for completion, streaming live output."""
    _check_notebooks()
    console.print(f"[bold cyan][RUN][/] Running job: {job_name} (streaming output — waiting for completion...)")
    _run_streaming(f"databricks bundle run {job_name}", cwd=REPO_ROOT)
    console.print(f"[green]  ✓ Job completed: {job_name}[/]")


def create_pr(use_case_name: str) -> str:
    """
    Commit all generated files and raise a GitHub PR.

    Flow:
      1. Create branch feat/<use-case-name>-generated-<timestamp>
      2. Stage generated files: project/notebooks/, project/tests/,
         project/docs/, project/demo/, project/specs/,
         project/use-cases/<name>/specs/
      3. Commit
      4. Push to origin
      5. gh pr create → returns PR URL

    Returns:
        PR URL string, or empty string if gh CLI is unavailable.
    """
    branch = "securities-master-dev"

    try:
        repo = git.Repo(STATESTREET_ROOT)
    except git.InvalidGitRepositoryError:
        console.print("[yellow][DEPLOY] Not a git repo — skipping PR creation.[/]")
        return ""

    # 1. Checkout existing branch or create new one
    console.print(f"[bold cyan][DEPLOY][/] Checking out branch: {branch}")
    if branch in repo.heads:
        repo.heads[branch].checkout()
    else:
        repo.create_head(branch).checkout()

    # 2. Stage entire repo (agentic/ + project/), respects .gitignore
    repo.git.add(A=True)

    # Check if anything was actually staged
    if not repo.index.diff("HEAD") and not repo.untracked_files:
        console.print("[yellow][DEPLOY] Nothing new to commit — PR skipped.[/]")
        return ""

    # 3. Commit
    commit_msg = (
        f"feat: generated notebooks, tests, and docs for {use_case_name}\n\n"
        f"Generated by SML BMAD pipeline.\n"
        f"Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
    )
    repo.index.commit(commit_msg)
    console.print(f"[green]  ✓ Committed generated files[/]")

    # 4. Push
    console.print(f"[bold cyan][DEPLOY][/] Pushing branch to origin...")
    origin = repo.remote("origin")
    origin.push(refspec=f"{branch}:{branch}", set_upstream=True)
    console.print(f"[green]  ✓ Pushed: {branch}[/]")

    # 5. Create PR via gh CLI
    pr_title = f"feat: generated pipeline for {use_case_name}"
    pr_body = (
        f"## Summary\n"
        f"- Generated Bronze/Silver/Gold notebooks for `{use_case_name}`\n"
        f"- Generated pytest test files (test_bronze.py, test_silver.py, test_gold.py)\n"
        f"- Generated documentation (lineage.md, hld.md, genie_comments.sql)\n\n"
        f"## Test plan\n"
        f"- [ ] Review generated notebooks in `project/notebooks/`\n"
        f"- [ ] Run `pytest project/tests/` locally\n"
        f"- [ ] Deploy bundle: `sml deploy --use-case {use_case_name}`\n"
        f"- [ ] Trigger bronze job: `sml run --use-case {use_case_name} --job bronze_ingest_job`\n\n"
        f"🤖 Generated with [SML BMAD Pipeline](https://github.com/anthropics/claude-code)"
    )

    pr_url = ""
    try:
        result = subprocess.run(
            ["gh", "pr", "create",
             "--title", pr_title,
             "--body",  pr_body,
             "--head",  branch,
             "--base",  "main"],
            cwd=STATESTREET_ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            pr_url = result.stdout.strip()
            console.print(f"\n[bold green][DEPLOY] PR created: {pr_url}[/]")
        else:
            console.print(f"[yellow][DEPLOY] gh pr create failed: {result.stderr.strip()}[/]")
            console.print(f"  Create PR manually from branch: {branch}")
    except FileNotFoundError:
        console.print("[yellow][DEPLOY] gh CLI not found. Install: brew install gh[/]")
        console.print(f"  Create PR manually from branch: {branch}")

    return pr_url


def _run(cmd: str, cwd: Path):
    result = subprocess.run(cmd.split(), cwd=cwd, capture_output=True, text=True)
    if result.stdout:
        console.print(result.stdout)
    if result.returncode != 0:
        err = result.stderr.strip() or result.stdout.strip()
        console.print(f"[red]{err}[/]")
        raise RuntimeError(f"Command failed: {cmd}\n{err}")


def _run_streaming(cmd: str, cwd: Path):
    """Run a command and stream stdout/stderr to console in real time."""
    process = subprocess.Popen(
        cmd.split(),
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    for line in process.stdout:
        print(line, end="", flush=True)
    process.wait()
    if process.returncode != 0:
        raise RuntimeError(f"Command failed: {cmd}")
